### PR TITLE
Use only necessary lodash modules

### PR DESCRIPTION
**Pull request by mlnchk**
Hi! Thanks for your work.
Noticed that the entire library uses lodash. For example, on bundlephobia it takes up 19kb — https://bundlephobia.com/result?p=@lifeomic/axios-fetch@1.4.1
Replaced all the calls with modules - this seems to help a lot.

### CODE REVIEW

**Comment by mdlavin** [comment]
The intention of the function specific imports was to allow webpack to reduce the size of the bundle. Are you not seeing that behavior?

**Comment by mlnchk** [comment]
Yes, i don't see.
I tried my version on my project and saw the bundle shrink (pic. 2).

Version from npm:
Screenshot 2019-12-20 at 12 34 31

My version from github:
Screenshot 2019-12-20 at 12 35 22

The changes seem to be small, because some libraries also pull the lodash.

**Comment by mdlavin** [comment]
Thanks for the data to support the change. Perhaps I should use this approach in more projects.

**Comment by mdlavin** [comment]
I pushed version v1.4.2 with this fix. It'll build and publish via Travis over the next couple of minutes

**Comment by mlnchk** [comment]
Now it's smaller 🍾
image

**Comment by mdlavin** [comment]
Thank you for spending time on this!

**Pull request merged**
